use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::crypto::agility::{verify_signature_by_algorithm, KeyAlgorithm};
use crate::pki::ca::CaDeclaration;

/// Operational reason classification for executing a key rotation under a CA (CA-09)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum RotationReason {
    /// Routine key life-cycle hygiene or periodic scheduled replacement
    RoutineOperational,
    /// Proactive key replacement following suspected exposure or side-channel threat
    SuspectedLeakage,
    /// Critical replacement following verified compromise of offer key material
    CompromisedKey,
    /// Comprehensive key rotation proving renewal of all active offer keys to remediate distrust (REP-09)
    DistrustRemediation,
    /// Custom operator-defined justification
    Other(String),
}

/// Cryptographic rotation record for a specific certificate offer key (CA-09)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OfferKeyRotation {
    pub offer_id: u32,
    pub old_public_key: Vec<u8>,
    pub new_public_key: Vec<u8>,
    pub key_algorithm: KeyAlgorithm,
    /// Digital signature over canonical PoP payload generated by the NEW keypair
    pub proof_of_possession: Vec<u8>,
    /// Optional signature over revocation payload generated by the OLD keypair
    #[serde(default)]
    pub old_key_revocation_signature: Option<Vec<u8>>,
}

impl OfferKeyRotation {
    /// Constructs the canonical message bytes for Proof-of-Possession (PoP)
    pub fn compute_pop_payload(
        ca_id: &[u8; 32],
        offer_id: u32,
        new_public_key: &[u8],
        timestamp: u64,
    ) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"randbotd_v1_offer_pop_domain:");
        hasher.update(ca_id);
        hasher.update(offer_id.to_le_bytes());
        hasher.update(new_public_key);
        hasher.update(timestamp.to_le_bytes());
        hasher.finalize().to_vec()
    }

    /// Verifies Proof-of-Possession (PoP) signature against the new public key
    pub fn verify_proof_of_possession(
        &self,
        ca_id: &[u8; 32],
        timestamp: u64,
    ) -> Result<(), String> {
        if self.new_public_key.is_empty() {
            return Err(format!(
                "Offer {} new_public_key cannot be empty",
                self.offer_id
            ));
        }
        if self.proof_of_possession.is_empty() {
            return Err(format!(
                "Offer {} proof_of_possession cannot be empty",
                self.offer_id
            ));
        }
        let payload =
            Self::compute_pop_payload(ca_id, self.offer_id, &self.new_public_key, timestamp);
        verify_signature_by_algorithm(
            self.key_algorithm,
            &self.new_public_key,
            &payload,
            &self.proof_of_possession,
        )
        .map_err(|e| {
            format!(
                "Offer {} Proof-of-Possession verification failed: {}",
                self.offer_id, e
            )
        })
    }
}

/// Cryptographically chained Key Rotation Proof record (CA-09)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct KeyRotationProof {
    pub proof_id: [u8; 32],
    pub ca_id: [u8; 32],
    pub rotation_seq: u64,
    pub prev_rotation_hash: [u8; 32],
    pub timestamp: u64,
    pub reason: RotationReason,
    pub rotations: Vec<OfferKeyRotation>,
    pub ca_signature: Vec<u8>,
}

impl KeyRotationProof {
    /// Computes the deterministic 32-byte cryptographic digest of this rotation record
    pub fn compute_hash(
        ca_id: &[u8; 32],
        rotation_seq: u64,
        prev_rotation_hash: &[u8; 32],
        timestamp: u64,
        reason: &RotationReason,
        rotations: &[OfferKeyRotation],
    ) -> [u8; 32] {
        let mut hasher = Sha256::new();
        hasher.update(b"randbotd_v1_key_rotation_proof:");
        hasher.update(ca_id);
        hasher.update(rotation_seq.to_le_bytes());
        hasher.update(prev_rotation_hash);
        hasher.update(timestamp.to_le_bytes());
        if let Ok(reason_bytes) = serde_json::to_vec(reason) {
            hasher.update(&reason_bytes);
        }
        for rot in rotations {
            hasher.update(rot.offer_id.to_le_bytes());
            hasher.update(&rot.old_public_key);
            hasher.update(&rot.new_public_key);
            hasher.update(rot.key_algorithm.oid().as_bytes());
            hasher.update(&rot.proof_of_possession);
            if let Some(ref rev) = rot.old_key_revocation_signature {
                hasher.update(rev);
            }
        }
        let res = hasher.finalize();
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&res);
        hash
    }

    /// Constructs, signs, and seals a new KeyRotationProof
    pub fn new(
        ca_id: [u8; 32],
        rotation_seq: u64,
        prev_rotation_hash: [u8; 32],
        timestamp: u64,
        reason: RotationReason,
        rotations: Vec<OfferKeyRotation>,
        ca_signing_key: &SigningKey,
    ) -> Result<Self, String> {
        if rotation_seq == 0 {
            return Err("rotation_seq must be >= 1 (1-based sequence)".to_string());
        }
        if rotation_seq == 1 && prev_rotation_hash != [0u8; 32] {
            return Err(
                "Genesis rotation (seq=1) must have prev_rotation_hash = [0; 32]".to_string(),
            );
        }
        if rotations.is_empty() {
            return Err("KeyRotationProof must contain at least one offer rotation".to_string());
        }

        // Validate each offer rotation's Proof-of-Possession
        for rot in &rotations {
            rot.verify_proof_of_possession(&ca_id, timestamp)?;
        }

        let proof_id = Self::compute_hash(
            &ca_id,
            rotation_seq,
            &prev_rotation_hash,
            timestamp,
            &reason,
            &rotations,
        );

        let signature: Signature = ca_signing_key.sign(&proof_id);

        Ok(Self {
            proof_id,
            ca_id,
            rotation_seq,
            prev_rotation_hash,
            timestamp,
            reason,
            rotations,
            ca_signature: signature.to_vec(),
        })
    }

    /// Verifies the CA node identity signature over this proof
    pub fn verify_ca_signature(&self, ca_owner_pubkey: &[u8]) -> Result<(), String> {
        if ca_owner_pubkey.len() != 32 {
            return Err(format!(
                "Invalid Ed25519 CA owner public key length {}",
                ca_owner_pubkey.len()
            ));
        }
        let mut pubkey_bytes = [0u8; 32];
        pubkey_bytes.copy_from_slice(ca_owner_pubkey);
        let verifying_key = VerifyingKey::from_bytes(&pubkey_bytes)
            .map_err(|e| format!("Invalid Ed25519 verifying key: {}", e))?;

        if self.ca_signature.len() != 64 {
            return Err(format!(
                "Invalid CA signature length {}",
                self.ca_signature.len()
            ));
        }
        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(&self.ca_signature);
        let signature = Signature::from_bytes(&sig_bytes);

        verifying_key
            .verify(&self.proof_id, &signature)
            .map_err(|e| format!("CA digital signature verification failed: {}", e))
    }

    /// Validates proof integrity, anti-solipsism sequence continuity, and cryptographic signatures
    pub fn validate(
        &self,
        ca: &CaDeclaration,
        ca_owner_pubkey: &[u8],
        prev_proof: Option<&KeyRotationProof>,
    ) -> Result<(), String> {
        if self.ca_id != ca.ca_id {
            return Err("Proof ca_id does not match target CA declaration ca_id".to_string());
        }

        let expected_ca_id =
            crate::pki::ca::compute_ca_id(&ca.subject.common_name, ca_owner_pubkey);
        if ca.ca_id != expected_ca_id {
            return Err("CA owner public key does not match CA identity binding (non-owner signature rejected)".to_string());
        }

        let expected_hash = Self::compute_hash(
            &self.ca_id,
            self.rotation_seq,
            &self.prev_rotation_hash,
            self.timestamp,
            &self.reason,
            &self.rotations,
        );
        if self.proof_id != expected_hash {
            return Err("Computed proof_id does not match declared proof_id".to_string());
        }

        match prev_proof {
            None => {
                if self.rotation_seq != 1 {
                    return Err(format!(
                        "Genesis rotation must have seq 1, got {}",
                        self.rotation_seq
                    ));
                }
                if self.prev_rotation_hash != [0u8; 32] {
                    return Err(
                        "Genesis rotation (seq 1) must have prev_rotation_hash = [0; 32]"
                            .to_string(),
                    );
                }
            }
            Some(prev) => {
                if self.rotation_seq != prev.rotation_seq + 1 {
                    return Err(format!(
                        "Invalid rotation_seq {}: expected {}",
                        self.rotation_seq,
                        prev.rotation_seq + 1
                    ));
                }
                if self.prev_rotation_hash != prev.proof_id {
                    return Err(
                        "Broken chain: prev_rotation_hash does not match previous proof_id"
                            .to_string(),
                    );
                }
                if self.timestamp < prev.timestamp {
                    return Err(format!(
                        "Timestamp regression: {} < previous {}",
                        self.timestamp, prev.timestamp
                    ));
                }
            }
        }

        // Verify each offer Proof-of-Possession
        for rot in &self.rotations {
            rot.verify_proof_of_possession(&self.ca_id, self.timestamp)?;
        }

        // Verify CA identity signature
        self.verify_ca_signature(ca_owner_pubkey)?;

        Ok(())
    }

    /// Returns true if this proof rotates all active offers belonging to the CA
    pub fn covers_all_offers(&self, active_offer_ids: &[u32]) -> bool {
        if active_offer_ids.is_empty() {
            return false;
        }
        let rotated_ids: std::collections::HashSet<u32> =
            self.rotations.iter().map(|r| r.offer_id).collect();
        active_offer_ids.iter().all(|id| rotated_ids.contains(id))
    }

    /// Determines if this proof qualifies to reset market distrust strikes
    ///
    /// Distrust remediation requires proving rotation of ALL active offer keys.
    pub fn can_reset_distrust(&self, active_offer_ids: &[u32]) -> bool {
        self.covers_all_offers(active_offer_ids)
    }
}

#[cfg(test)]
mod tests;
